name: Update from Repository A

on:
  schedule:
    - cron: '0 * * * *' # Run every hour
  workflow_dispatch: # Allow manual trigger

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2

      - name: Checkout Repository A
        uses: actions/checkout@v2
        with:
          repository: sun532818microbit/Clock-V2
          token: ${{ secrets.REPO_A_PAT }}
          path: repo-a

      - name: Copy index.html from Repository A to Repository B
        run: cp repo-a/index.html ./index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html
          git commit -m 'Update from Repository A'
          git push
